Repository microsoft/vscode-docs, pull requests merged in 2019-02, with the labels that each got.

#2398 [api/extension-guides/icon-theme] Fix typos in guide
  api/extension-guides/icon-theme.md
Labels: extensibility

#2400 [api/extension-guides/virtual-documents] Fix typos in guide
  api/extension-guides/virtual-documents.md
Labels: extensibility

#2399 [api/extension-guides/debugger-extension] Fix typos in guide
  api/extension-guides/debugger-extension.md
Labels: extensibility

#2417 update wording with new behavior
  docs/setup/linux.md
Labels: Linux

#2418 Update contribution-points.md
  api/references/contribution-points.md
Labels: extensibility

#2438 Format of inc_dec.py snippet in unit-testing.md
  docs/python/unit-testing.md
Labels: python
