Repository microsoft/vscode-docs, pull requests merged in 2019-01, with the labels that each got.

#2310 Unpin links to a specific version of Python
  docs/python/environments.md
Labels: python

#2331 fix typo for grammar scopes example
  api/language-extensions/syntax-highlight-guide.md
Labels: extensibility

#2332 Syntax highlighting uses Oniguruma regular expressions
  api/language-extensions/syntax-highlight-guide.md
Labels: extensibility

#2335 Fix Syntax Highlighting Yaml Section
  api/language-extensions/syntax-highlight-guide.md
Labels: extensibility

#2336 Update file path in tutorial-djanjo.md
  docs/python/tutorial-django.md
Labels: python

#2348 contribution-points.md, fix broken link
  api/references/contribution-points.md
Labels: extensibility

#2349 Update overview.md
  api/extension-guides/overview.md
Labels: extensibility

#2367 Update the gif for Java Test Runner
  docs/languages/images/java/testng.gif
Labels: java
