Repository microsoft/vscode-docs, pull requests merged in 2020-02, with the labels that each got.

#3377 Add Github Actions to CI documentation
  api/working-with-extensions/continuous-integration.md
Labels: extensibility

#3382 Execution policy hint
  docs/python/environments.md
Labels: python

#3398 Minor grammar fix
  api/language-extensions/language-server-extension-guide.md
Labels: extensibility

#3402 Add documentation on lldb-mi for cpptools
  docs/cpp/images/debugger/DeveloperToolsAccess.png
  docs/cpp/lldb-mi.md
Labels: C++, don't merge

#3414 Java 2020 Feb. updates
  docs/java/images/java-debugging/thread-context-menu.png
  docs/java/images/java-project/manage-dependencies.gif
  docs/java/images/java-project/maven-add-dependency-2.mp4
  docs/java/java-debugging.md
  docs/java/java-editing.md
  docs/java/java-project.md
Labels: java

#3342 Custom Data blog post
  blogs/2019/11/26/custom-data-format.md
  blogs/2019/11/26/custom-data-helloworld.png
  blogs/2019/11/26/html-css-language-features.png
  blogs/2019/11/26/mavo-demo.gif
  blogs/2019/11/26/simple-interface.png
Labels: extensibility

#3419 Update c-cpp-properties-schema-reference.md
  docs/cpp/c-cpp-properties-schema-reference.md
Labels: C++
