Repository microsoft/vscode-docs, pull requests merged in 2022-05, with the labels that each got.

#5308 update Python 3.9 references, image, and refresh feature
  docs/python/environments.md
  docs/python/images/environments/conda-environment-refresh.png
Labels: python

#5307 update content, ms.date, and run acrolinx
  docs/python/images/linting/enable-linting-dropdown.png
  docs/python/linting.md
Labels: python

#5316 Update view progress guideline
  api/ux-guidelines/views.md
Labels: extensibility

#5278 updating the run/debug tutorials to reflect new play button and F5 behavior
  docs/cpp/config-clang-mac.md
  docs/cpp/config-linux.md
  docs/cpp/config-mingw.md
  docs/cpp/config-msvc.md
  docs/cpp/config-wsl.md
  docs/cpp/images/playbutton/add-debug-configuration.png
  docs/cpp/images/playbutton/breakpoint-debug.png
  docs/cpp/images/playbutton/compiler-list.png
  docs/cpp/images/playbutton/cpp-breakpoint.png
  docs/cpp/images/playbutton/debug-button.png
  docs/cpp/images/playbutton/debug-cpp-file-play-button.png
  docs/cpp/images/playbutton/dev-command-prompt-error.png
  docs/cpp/images/playbutton/helloworld-terminal-output.png
  docs/cpp/images/playbutton/new-playbutton-dropdown.png
  docs/cpp/images/playbutton/run-debug-arrow.png
  docs/cpp/images/playbutton/run-debug-drop-down.png
  docs/cpp/images/playbutton/run-play-button.png
  docs/cpp/images/playbutton/select-cl-compiler.png
  docs/cpp/images/playbutton/select-clang-compiler.png
  docs/cpp/images/playbutton/select-gcc-compiler.png
  docs/languages/images/cpp/gcc-compiler-list.png
  docs/languages/images/cpp/select-environment.png
  docs/languages/images/cpp/start-build-output.png
  docs/languages/images/cpp/successful-build-output.png
  docs/languages/images/cpp/terminal-output.png
Labels: don't merge, C++

#5337 updating the run/debug tutorials
  docs/cpp/config-clang-mac.md
  docs/cpp/config-linux.md
  docs/cpp/config-mingw.md
  docs/cpp/config-msvc.md
  docs/cpp/config-wsl.md
  docs/cpp/images/playbutton/add-debug-configuration.png
  docs/cpp/images/playbutton/new-playbutton-dropdown.png
Labels: C++

#5338 updating flask/django docs with env UI changes
  docs/python/images/shared/environment-in-status-bar.png
  docs/python/tutorial-django.md
  docs/python/tutorial-flask.md
Labels: python, doc-bug

#5343 fix typo
  docs/cpp/config-linux.md
Labels: C++

#5329 Rebrand .NET Core > .NET
  docs/containers/choosing-dev-environment.md
  docs/containers/debug-common.md
  docs/containers/debug-netcore.md
  docs/containers/docker-compose.md
  docs/containers/overview.md
  docs/containers/quickstart-aspnet-core.md
  docs/containers/reference.md
Labels: don't merge, containers

#5350 remove mention of 'code' as alt to 'module'
  docs/python/debugging.md
Labels: python, doc-bug

#5347 Dev containers blog
  blogs/2022/05/18/dev-container-cli.md
  blogs/2022/05/18/dev-container-stages.png
Labels: remote

#5361 Update dev container blog post
  blogs/2022/05/18/dev-container-cli.md
Labels: remote
