Repository microsoft/vscode-docs, pull requests merged in 2023-12, with the labels that each got.

#6818 Update vscode.dev URLs
  docs/editor/vscode-web.md
Labels: don't merge

#6876 Replace quickFixWidgetVisible with codeActionMenuVisible
  api/references/when-clause-contexts.md
Labels: extensibility

#6915 Update Mac Clang Docs
  docs/cpp/config-clang-mac.md
  docs/cpp/config-mingw.md
  docs/cpp/images/clang-mac/build-and-debug-active-file.png
  docs/cpp/images/clang-mac/clang-task-in-terminal.png
  docs/cpp/images/clang-mac/default-build-task.png
  docs/cpp/images/clang-mac/helloworld-debug-console-output.png
  docs/cpp/images/clang-mac/helloworld-in-terminal.png
  docs/cpp/images/clang-mac/helloworld-terminal-output.png
Labels: C++

#6925 Update guide to match latest vue version
  docs/nodejs/images/vuejs/create-vue.png
  docs/nodejs/images/vuejs/hello-world.png
  docs/nodejs/images/vuejs/javascript-suggestions.png
  docs/nodejs/images/vuejs/peek-definition.png
  docs/nodejs/images/vuejs/suggestions.png
  docs/nodejs/images/vuejs/vetur-extension-recommendation.png
  docs/nodejs/images/vuejs/vetur-extension.png
  docs/nodejs/images/vuejs/volar-extension-recommendation.png
  docs/nodejs/images/vuejs/volar-extension.png
  docs/nodejs/images/vuejs/vue-app-scaffolding.png
  docs/nodejs/images/vuejs/vue-extension-pack.png
  docs/nodejs/images/vuejs/vue-extensions.png
  docs/nodejs/images/vuejs/vue-language-features.png
  docs/nodejs/images/vuejs/vue-recommended-extensions.png
  docs/nodejs/images/vuejs/vue-vscode-snippets.png
  docs/nodejs/images/vuejs/welcome-to-vue.png
  docs/nodejs/vuejs-tutorial.md
Labels: don't merge
