Repository microsoft/vscode-docs, pull requests merged in 2023-09, with the labels that each got.

#6630 Document more tunneling / CLI options
  docs/remote/tunnels.md
Labels: remote, doc-enhancement

#6631 Adding UCRT support for MinGW
  docs/cpp/config-mingw.md
  docs/languages/cpp.md
Labels: C++

#6649 Update Screenshots for UCRT
  docs/cpp/config-mingw.md
  docs/cpp/images/cpp/cpp-install-MSYS2-toolchain.png
  docs/languages/cpp.md
  docs/languages/images/cpp/cpp-install-msys2-toolchain.png
Labels: C++

#6658 Update remote faq
  docs/remote/faq.md
Labels: remote

#6638 fix incorrect extension entry point
  api/extension-guides/webview.md
Labels: extensibility

#6641 Add section on always installed features
  docs/devcontainers/containers.md
Labels: remote

#6675 Document new terminal menu contribution points
  api/references/contribution-points.md
Labels: extensibility
