Repository microsoft/vscode-docs, pull requests merged in 2023-11, with the labels that each got.

#6777 Edits to Python tutorial
  docs/languages/python.md
  docs/python/python-tutorial.md
Labels: python

#6787 Update port forwarding and Remote-Tunnels docs
  docs/editor/port-forwarding.md
  docs/remote/tunnels.md
Labels: remote, doc-enhancement

#6614 Add IntelliSense Configuration Doc
  docs/cpp/c-cpp-properties-schema-reference.md
  docs/cpp/configure-intellisense-crosscompilation.md
  docs/cpp/configure-intellisense.md
  docs/cpp/faq-cpp.md
  docs/cpp/images/intellisense/compiler-quick-pick.png
  docs/cpp/images/intellisense/configure-intellisense-indicator.png
  docs/cpp/images/intellisense/language-status-bar.png
Labels: C++

#6807 Fix grammatical error in line 69
  docs/cpp/config-mingw.md
Labels: C++

#6798 Adding VS Code for Edu link to Python tutorial
  docs/python/python-tutorial.md
Labels: python

#6780 Sinemakinci/newcmakestatusbar
  docs/cpp/cmake-linux.md
  docs/cpp/images/cpp/build-target.png
  docs/cpp/images/cpp/cmake-build-v2.png
  docs/cpp/images/cpp/cmake-build.png
  docs/cpp/images/cpp/cmake-kit-statusbar.png
  docs/cpp/images/cpp/cmake-kit.png
Labels: C++

#6771 Fix recommended dotfiles install command
  docs/devcontainers/containers.md
  docs/devcontainers/images/containers/dotfiles.png
Labels: remote

#6593 docs(extension management): refactor extension management sections to be more concise
  api/working-with-extensions/images/publishing-extension/publisher-details-tab-verified-domain.png
  api/working-with-extensions/images/publishing-extension/publisher-details-tab.png
  api/working-with-extensions/images/publishing-extension/saved-domain-to-verify.png
  api/working-with-extensions/images/publishing-extension/sponsor-link-example.png
  api/working-with-extensions/images/publishing-extension/sponsor.png
  api/working-with-extensions/images/publishing-extension/txt-record-verification.png
  api/working-with-extensions/images/publishing-extension/validation-submitted.png
  api/working-with-extensions/images/publishing-extension/verified-publisher-manage.png
  api/working-with-extensions/images/publishing-extension/verified-publisher.png
  api/working-with-extensions/images/publishing-extension/verified-publishers.png
  api/working-with-extensions/publishing-extension.md
Labels: extensibility

#6849 Updated connect to multiple containers command
  remote/advancedcontainers/connect-multiple-containers.md
Labels: remote
