Repository microsoft/vscode-docs, pull requests merged in 2023-02, with the labels that each got.

#6003 Update contribution-points.md
  api/references/contribution-points.md
Labels: extensibility

#6002 Explain how to order & group Tree View actions
  api/extension-guides/tree-view.md
Labels: extensibility

#6023 Improve description of the `contributes.viewContainers` id property
  api/extension-guides/tree-view.md
Labels: extensibility

#6022 Extension display name and publisher display name new restrictions
  api/references/extension-manifest.md
  api/working-with-extensions/publishing-extension.md
Labels: extensibility

#6041 Add pytest fixtures support with Pylance
  docs/python/images/testing/pytest-annotation-code-action.png
  docs/python/images/testing/pytest-fixture-autocomplete.png
  docs/python/images/testing/pytest-inferred-parametrized-argument.png
  docs/python/settings-reference.md
  docs/python/testing.md
Labels: python

#6049 Add dev container artifact distribution info
  docs/devcontainers/containers.md
  docs/devcontainers/devcontainer-cli.md
Labels: remote

#6047 Add curl install info to tunneling doc
  docs/remote/tunnels.md
Labels: remote

#6055 Remove mentions of Python 2
  docs/python/editing.md
  docs/python/environments.md
  learn/develop-cloud/overview.md
Labels: python

#6068 Update remote indicator content
  docs/devcontainers/images/tutorial/dev-containers-commands-simple.png
  docs/devcontainers/images/tutorial/dev-containers-commands.png
  docs/devcontainers/tutorial.md
  docs/remote/images/ssh-tutorial/remote-commands-simple.png
  docs/remote/images/ssh-tutorial/remote-commands.png
  docs/remote/images/wsl-tutorial/remote-wsl-commands.png
  docs/remote/images/wsl-tutorial/wsl-commands.png
  docs/remote/ssh-tutorial.md
  docs/remote/wsl-tutorial.md
Labels: remote, doc-enhancement

#6081 fix: typo in property "highContrastLight" of the colors contribution point
  api/references/contribution-points.md
Labels: extensibility

#6087 Add doc note to GitHub Repos blog
  blogs/2021/06/10/remote-repositories.md
Labels: doc-enhancement

#6028 Add info about deployment to ACA from Docker
  docs/containers/app-service.md
  docs/containers/overview.md
  docs/containers/quickstart-aspnet-core.md
  docs/containers/quickstart-container-registries.md
  docs/containers/quickstart-python.md
Labels: don't merge, containers

#6056 Update formatting example
  api/language-extensions/programmatic-language-features.md
Labels: extensibility
