Repository microsoft/vscode-docs, pull requests merged in 2024-03, with the labels that each got.

#7076 Added the support.md file documentation
  api/working-with-extensions/publishing-extension.md
Labels: doc-enhancement

#6997 Fix incorrect code sample in api/extension-guides/webview.md
  api/extension-guides/webview.md
Labels: doc-bug

#7153 Update linux.md
  docs/remote/linux.md
Labels: remote
