Repository microsoft/vscode-docs, pull requests merged in 2025-05, with the labels that each got.

#8283 Add Azure Resources doc
  docs/azure/aksextensions.md
  docs/azure/deployment.md
  docs/azure/docker.md
  docs/azure/images/extensions/accountsAndTenants.png
  docs/azure/images/extensions/authenticateTenant.png
  docs/azure/images/extensions/cloudOptions.png
  docs/azure/images/extensions/filterSub.png
  docs/azure/images/extensions/multiAccount.png
  docs/azure/images/extensions/signInCommandPallete.png
  docs/azure/images/extensions/signInView.png
  docs/azure/images/extensions/signOut.png
  docs/azure/kubernetes.md
  docs/azure/mongodb.md
  docs/azure/remote-debugging.md
  docs/azure/resourcesextension.md
  docs/toc.json
Labels: info-needed

#8379 fix: grammar on linters section
  docs/languages/javascript.md
Labels: info-needed

#8051 Add swift language documentation
  docs/languages/images/swift/build-tasks.png
  docs/languages/images/swift/configuration.png
  docs/languages/images/swift/configure-lldb.png
  docs/languages/images/swift/debugging.png
  docs/languages/images/swift/inline_assertion_failures.png
  docs/languages/images/swift/installation.png
  docs/languages/images/swift/package_actions.png
  docs/languages/images/swift/reload.png
  docs/languages/images/swift/select-project-template.png
  docs/languages/overview.md
  docs/languages/swift.md
Labels: doc-enhancement

#8426 Updating Note on VS license
  docs/cpp/config-msvc.md
Labels: C++
