Repository microsoft/vscode-docs, pull requests merged in 2025-04, with the labels that each got.

#8297 Update prompt builder documentation to agent builder
  docs/intelligentapps/agentbuilder.md
  docs/intelligentapps/images/promptbuilder/AgentBuilder.gif
  docs/intelligentapps/images/promptbuilder/Featured_server.png
  docs/intelligentapps/images/promptbuilder/MCPScaffold.gif
  docs/intelligentapps/images/promptbuilder/config_server.png
  docs/intelligentapps/images/promptbuilder/edit_schema_2.png
  docs/intelligentapps/images/promptbuilder/generate_prompt_2.gif
  docs/intelligentapps/images/promptbuilder/mcp_debug.gif
  docs/intelligentapps/images/promptbuilder/mcp_existing.gif
  docs/intelligentapps/images/promptbuilder/scaffold_mcp.gif
  docs/intelligentapps/images/promptbuilder/select_models.png
  docs/intelligentapps/images/promptbuilder/structured_output_2.gif
  docs/intelligentapps/images/promptbuilder/view_code_2.gif
  docs/intelligentapps/promptbuilder.md
  docs/toc.json
Labels: don't merge

#8321 Document VSCODE_EXTENSIONS environment variable
  docs/configure/extensions/extension-marketplace.md
Labels: doc-enhancement

#8310 Update C++ Settings doc
  docs/cpp/c-cpp-properties-schema-reference.md
  docs/cpp/customize-cpp-settings.md
  docs/cpp/customize-default-settings-cpp.md
  docs/toc.json
Labels: C++
